# Generated by Django 5.2.4 on 2025-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articleImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
